### ISSUE TITLE
Can't update ME firmware on Thinkpad L13 gen1 to 225.67.2046

### ISSUE THREAD

**Issue by p4block** [fwupd/firmware-lenovo#306]
I'm on latest UEFI firmware, even downgraded to see if that fixed anything and tried some workarounds people discussed on similar threads such as enabling csm to no avail.

Current ME fw version is 225.53.1649, verified by looking at the UEFI firmware menu.

When rebooting to update fwupd efi binary briefly prints to screen something about capsule/device error and reboots. 

```
 sudo fwupdmgr update
Devices with no available firmware updates: 
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
╔══════════════════════════════════════════════════════════════════════════════╗
║ Upgrade Intel Management Engine from 225.53.1649 to 225.67.2046?             ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ Lenovo ThinkPad L13 Consumer ME Firmware en_US update MEFW 14.1.67.2046      ║
║                                                                              ║
║ Hot Fix Release U/Y/S/H  Disable auto-sleep when the device is connected to  ║
║ a USB port  Improve performance of the analog sticks Some new functionality  ║
║ has also been added:  Add support for Joystick Mode to OS X                  ║
║                                                                              ║
║ 20R30004SP must remain plugged into a power source for the duration of the   ║
║ update to avoid damage.                                                      ║
╚══════════════════════════════════════════════════════════════════════════════╝
```

Additionally, I think that changelog for an ME update is quite weird and may be a mixup (macOS? Joysticks?? Is this an 8bitdo firmware? :smile:  )

**Comment by hughsie** [comment]
I've fixed the update release notes; the default text was used by the uploader somehow :)

> something about capsule/device error

Can you video it and get the exact message please?

**Comment by p4block** [comment]
![image](https://user-images.githubusercontent.com/5960575/210410370-badcd50a-5968-46bd-aa6b-972937cd5be7.png)

(transcribing for search engine-ability)
```
fwupd-efi version 1.3
WARNING: Could not apply capsule update: Device Error
WARNING: Could not apply capsules: Device Error
Reset System
```

I forced a refresh and changelog still the same though, I guess it takes time to propagate :thinking: I see it's updated in the lvfs site.

**Comment by kmauleon** [comment]
hi... will ping the owner for this one... thank you for reporting

**Comment by kmauleon** [comment]
hi... new firmware was reuploaded can you please try?  thank you very much.
Corporate : https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadR15RM.firmware
Consumer : https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadR15RN.firmware

**Comment by p4block** [comment]
Updated now without issues :smile:
